 server:
   port: 8088

 spring:
   jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
         ddl-auto: update
      generate-ddl: true


   datasource:
      url: jdbc:postgresql://localhost:5432/Remainder
      username: postgres
      password: Venkatesh@08
      driver-class-name: org.postgresql.Driver

