 server:
   port: 8080

 spring:
   jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
         ddl-auto: update
      generate-ddl: true


   datasource:
      url: jdbc:postgresql://localhost:5432/Remainder
      username: postgres
      password: Venkatesh@08
      driver-class-name: org.postgresql.Driver

   jackson:
      property-naming-strategy: SNAKE_CASE

   mail:
      host: smtp.gmail.com
      port: 587
      username: venkatesh082001@gmail.com
      password: dwedwguvzxqlygld
      properties:
         mail:
           smtp:
              auth: true
              starttls:
                 enable: true


